name: Android Build (APK)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: npm install
        working-directory: ./thecoc-mobile

      - name: Generate Native Android Project
        run: npx expo prebuild --platform android
        working-directory: ./thecoc-mobile

      - name: Build Android APK
        working-directory: ./thecoc-mobile/android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Copy & Rename APK
        run: |
          mkdir -p Payload
          cp thecoc-mobile/android/app/build/outputs/apk/debug/app-debug.apk Payload/TheCoc-Android.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TheCoc-Android
          path: Payload/TheCoc-Android.apk
